### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by manni0815held** [nickpourazima/rotary-phone-audio-guestbook#2]
Hey,
can someone describe the project a little more for a beginner. I have no idea what to use and how to connect it.

Would really appreciate it.

Thank you

**Comment by nickpourazima** [comment]
Hey @manni0815held, I'm going to merge in some changes with better documentation and pictures soon - hopefully that can get you further along.

**Comment by nickpourazima** [comment]
Check out the latest and let me know if you've got any questions, thanks!
