### ISSUE TITLE
Greeting_Start_Delay only accepts 0 or whole seconds, fractional seconds in decimal seems to introduce breaking error 

### ISSUE THREAD

**Issue by Bonneykins** [nickpourazima/rotary-phone-audio-guestbook#36]
https://github.com/nickpourazima/rotary-phone-audio-guestbook/blob/4c8bbd84d1a8fc324ebc9d6e4963807a303974e4/config.yaml#L19C1-L19C24

Tried to input a 1.5 second Greeting Start Delay and caused an error.

Could not find documentation from aplay about what is or isn't supported as duration flag parameter.

Just note this with in-line documentation for the meantime?

**Comment by nickpourazima** [comment]
Thanks @Bonneykins for pointing that out! I'll look into it and keep you posted.

**Comment by nickpourazima** [comment]
Hi @Bonneykins, I'm working on an update for this along with some other fixes, just need a bit more time after work to validate. Should be able to get it out this weekend.
