### ISSUE TITLE
Wire mic with TRS Connector

### ISSUE THREAD

**Issue by kbn53** [nickpourazima/rotary-phone-audio-guestbook#39]
Hello,

Thanks for this beautiful project !

I'm stuck on the mic wire with TRS connector.

Look below :

I've these cable on my S63 

![439442159_326606643792442_4409066463879523692_n](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/c0ca5fc8-17de-4e5f-b9fb-84feb52ad837)

And I want to connect in both TRS like this 
![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/b56367b8-642a-4182-8ac7-1074f0d4609a)

Can you help me ?

**Comment by kbn53** [comment]
I try this, do you think is good ?

![438154274_647742497548020_3439792580971681064_n (1)](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/255e1564-25ea-4bf3-9f11-ab6fe1477d59)

Green and brown in GND
Red in R
Blue in T

**Comment by kbn53** [comment]
@nickpourazima Hi, I did this thing, can you tell me if it's the good way with these connector ?

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/797806e6-edd2-4526-98e4-00768997b1a9)

Green  = Microphone
Green = Microphone
Blue = Speaker
Red = Speaker

**Comment by nickpourazima** [comment]
Hi @kbn53, thanks for the kind words!

Your diagram looks solid 👍🏽 

However, I did some digging up on this phone and I believe there's another component at play here which looks to be reconfiguring some of the wiring:
![DSC05141](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/12181252/2a8ef46e-ef83-477a-9a9c-53b1bf8eca80)

Is that the case with your model? Or did you already remove that?

Referenced [here](https://www.vintage-radio.net/forum/showthread.php?t=119244)

Also, in-case you need it - here is a link to the [schematic](https://www.britishtelephones.com/diagrams/socotels63english.pdf)

**Comment by kbn53** [comment]
Thanks for your answer @nickpourazima 

With mine, "Socotel 63" I think is more recent and I don't have this component.

Only my mic/speaker with 4 cable (green, green, red and blue) 

2 for speaker and 2 for mic

Here is 2 pictures to show my model. I disconnected the PTT cable, I think it's not useful ?

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/071db028-7e53-4c4e-ba08-a0db1989425d)![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/9b96b29d-a2f7-4000-a7e6-6da36d24e1f8)

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/53c28994-9b94-4507-80af-2c6f3f8a1498)

**Comment by kbn53** [comment]
![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/0bedbe8a-1111-421a-8a52-aff3e4cdcc62)

**Comment by kbn53** [comment]
![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/259aeb40-02f1-4735-96e4-20519319891c)

Here is the schematic inside

**Comment by nickpourazima** [comment]
I'm not too familiar who those types of phones unfortunately. Does PTT stand for push-to-talk in this case? If so, I'd believe it would be necessary to leave that circuitry intact for the microphone to be enabled. It might be helpful to ask on this forum: https://www.classicrotaryphones.com/forum/index.php?board=1.0

**Comment by kbn53** [comment]
@nickpourazima Ok thanks !

For me the PTT socket is this cable that connects to the phone network normally and I remove it because for me it is not useful.

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/ebe9f97a-3bbc-4229-8145-b6a3a3b7e989)

I'm going to test this connection and I'll tell you if it works

**Comment by kbn53** [comment]
> > Salut, j’ai fait ce truc, pouvez-vous me dire si c’est la bonne façon avec ces connecteurs ?
> > ![image](https://private-user-images.githubusercontent.com/71877652/333331692-797806e6-edd2-4526-98e4-00768997b1a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1Njk5MTIsIm5iZiI6MTcxNjU2OTYxMiwicGF0aCI6Ii83MTg3NzY1Mi8zMzMzMzE2OTItNzk3ODA2ZTYtZWRkMi00NTI2LTk4ZTQtMDA3Njg5OTdiMWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE2NTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNDkxMTU1ZmM4YzA3MDE1ZWZkMjMxM2M3Njk5NzJiNGY4YmJjOGZkMjcxMTRkZDNhOWIwMzYzOGNjMWE5MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HX3pCtBeWMLhlnBVkFeQ4nGo-Eyvi-izMNZgTRGaTgs)
> > Vert = Microphone Vert = Microphone Bleu = Haut-parleur Rouge = Haut-parleur
> 
> Hé, je ne suis pas un expert en la matière, mais ce schéma de connexion semble raisonnable. Il convient de noter que pour un micro standard à deux bornes, je ne pense pas que le fil de liaison rouge, qui passe entre les deux bornes « S » de la masse / manchon dans votre dessin, fasse quoi que ce soit. En supposant que vous les branchiez toujours sur la même carte son, je suppose que cela n’endommagerait rien et pourrait être utile plus tard, si vous remplacez le microphone par un microphone qui a besoin de cette masse (pourrait voler la terre du côté du haut-parleur).
> 
> Question, si vous débranchez le connecteur TRS du haut-parleur, l’entrée microphone fonctionne-t-elle ? En [regardant https://images.app.goo.gl/dSkp43ZhgfHvvPEj6](https://images.app.goo.gl/dSkp43ZhgfHvvPEj6), il semble que le branchement d’une prise TRS normale dans la fente pour carte son compatible TRRS pourrait court-circuiter la broche du microphone avec la masse. Ainsi, si les ports sont câblés ensemble, cela peut essentiellement désactiver le microphone branché sur l’autre port.
> 
> De plus, il est possible que le microphone de votre combiné soit tout simplement trop hors spécifications pour être utilisé directement avec une carte son moderne (tension de polarisation, ...). Entendez-vous quelque chose sur l’enregistrement lorsque vous parlez dans le micro ? Si vous criez dans le micro, entendez-vous quelque chose sur l’enregistrement, même faible ? Assurez-vous d’utiliser une application d’enregistrement audio connue pour fonctionner, car nous ne voulons vraiment pas déboguer plusieurs couches de problèmes. Vous pouvez également brancher la carte audio USB sur votre ordinateur de bureau/portable pour vérifier le fonctionnement.
> 
> Avez-vous des photos du microphone lui-même ?
> 
> Tout le meilleur,
> 
> Craig
> 
> Pour info, voici un schéma pour utiliser un microphone mems avec une configuration normale de microphone à 2 fils :
> 
> https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://invensense.tdk.com/wp-content/uploads/2015/02/Using-a-MEMS-Microphone-in-a-2-Wire-Microphone-Circuit.pdf&ved=2ahUKEwjsv7bt5aaGAxWKADQIHbpEAs8QFnoECBIQAQ&usg=AOvVaw38B-gKcXNfdMPFtHeUdGb4

I @linux4life798 thanks for this answer. 

I think It's gonna be ok, I'll test this this afternoon. 

But yesterday, I try to connect my USB audio card in my PC and the speaker was good but the mic doesn't work.

**Comment by kbn53** [comment]
![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/2ed989dc-e516-41f5-8d20-ffe9fbc42496)

**Comment by kbn53** [comment]
Ok so, I finished (I think) my wire. But there is no action when I lift the speaker. In the service (journalctl -u audioGuestBook -f
) It mention that I need to lift but when I lift nothing happend.



![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/6f8a7049-a64b-490a-a095-639710a1be5b)

I see my USB Audio card in CARD 1 and DEVICE 0 and I configure it in .ascoudrc

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/7c75e9b2-db85-4214-8f71-0275f5415f2e)

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/53ece0d1-f5a9-48e1-bf4e-7e0050ac9f78)

I'm in NO (I think) but I try NC and it's the same issue.

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/b4de9265-41c9-4fa1-8c30-18bd2aeee38a)

I wire black cable on GND GPIO 3 and white one on GPIO 22 

![441370954_497449825996204_567584194327243143_n](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/c659f2fe-9d7d-41d9-bdce-8463f0a86616)

![441572179_1781353065708291_16566064194656038_n](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/d61e0658-515f-4e1e-b48c-ef95d44e2025)
![441877869_1609822819875183_2074185508054254321_n](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/6387337e-db1f-4eef-b643-70f95ab087c6)

Any idea of the problem ?

Thanks !

**Comment by kbn53** [comment]
So I've news

I succeeded once, but I can't reproduce ^^'

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/247f3b59-4c48-4a3f-8cc2-669dddf6b6e4)



I think my previous wire was wrong, I think these blue and pink cable or directly connected at the keypad and the hook so I try to work on these one.


![438158950_347837031313410_8991365702552911412_n](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/2f5ee9d1-d994-4c13-88cf-e2707ba80c55)
![441447678_934456471751675_5557010505899241732_n](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/4637a30f-78a4-47f9-b020-54bffb3b7d17)
![441877924_1502257880634288_2120265905161549765_n](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/2fb6afb8-880d-4407-83e2-3688eb05c6ba)

**Comment by kbn53** [comment]
....

I was on the bad GPIO. I replug on the good one GPIO22 and it's good.

Now I can hear the voicemail and the beep but last problem, recording stop after bip (Mic's not detected ? can't save file ?)

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/10c768dd-6910-46cd-9d7b-24ba642c1e88)

I'm searching

**Comment by nickpourazima** [comment]
Hey @kbn53, thanks for all the details and pictures, it's super helpful! One thing to check, did you set your config back to NO again? I think NO should be correct for you configuration.

**Comment by kbn53** [comment]
> Hey @kbn53, thanks for all the details and pictures, it's super helpful! One thing to check, did you set your config back to NO again? I think NO should be correct for you configuration.

Hey @nickpourazima no problem I try to save my conf but if it can help an other user it's cool !

Yes I'm in NO and this is working.

My last problem is after the BEEP It's directly Recording stopped and can't do anything.

Probably because my mic's not woking ? (If I connect my usb audio card on my windows I can use speaker for spotify for exemple but can't use for recording my voice)

**Comment by nickpourazima** [comment]
When you speak into the mic do you see any voltage variation? Probably set your multimeter to mV. 

Another thing I recall when I first tried using the built in carbon mic was that the amplitude is super low and may require being driven beyond what ALSA can do in the digital domain. If you have a headphone amplifier you might be able to test this?

**Comment by kbn53** [comment]
> When you speak into the mic do you see any voltage variation? Probably set your multimeter to mV.
> 
> Another thing I recall when I first tried using the built in carbon mic was that the amplitude is super low and may require being driven beyond what ALSA can do in the digital domain. If you have a headphone amplifier you might be able to test this?

Hmmm, I can't try to talk because the recording stopping directly I think

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/0efb6ad9-f045-468f-a11e-17ad8791c15a)

And I don't have amplifier sorry...

**Comment by nickpourazima** [comment]
Oh I meant checking the microphone hardware directly with the wires connected to the probes of your multimeter. 

But within a Linux terminal you can also try to open `alsamixer` and increase the mic gain. It might be labelled 'Capture', then once you're happy with your levels hit Esc and then this to save it upon reboot:
`sudo alsactl store`

**Comment by kbn53** [comment]
> Oh I meant checking the microphone hardware directly with the wires connected to the probes of your multimeter. 
> 
> 
> 
> But within a Linux terminal you can also try to open `alsamixer` and increase the mic gain. It might be labelled 'Capture', then once you're happy with your levels hit Esc and then this to save it upon reboot:
> 
> `sudo alsactl store`

If I understand, I connect my multimeter in mV here ? (yellow circle) 

And I talk and try to see if the value increase ?

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/22f7bc61-8a45-4d40-98ea-a97357dc68db)

I'll try too the alsamixing.

Also, you need to know that I disconnect the red bridge betweenf both TRS jack (like @linux4life798 said before) It was useless.

**Comment by nickpourazima** [comment]
That's correct, make sure to set your multimeter to millivolts AC and not DC

**Comment by kbn53** [comment]
> Oh, je voulais dire vérifier le matériel du microphone directement avec les fils connectés aux sondes de votre multimètre.
> 
> Mais dans un terminal Linux, vous pouvez également essayer d’ouvrir et d’augmenter le gain du micro. Il peut s’appeler « Capture », puis une fois que vous êtes satisfait de vos niveaux, appuyez sur Échap, puis ceci pour l’enregistrer au redémarrage :`alsamixer` `sudo alsactl store`

So I try to increase gain mics but nothing happend.

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/1fd274e5-e5e1-430b-8e46-8c1bfec5ea44)

I try too with multimeter (my wire is correct ?, I'm not good with this ^^')

![438158268_7944785022233432_7983236048045769899_n](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/171113d2-8984-44e5-b12d-d186ca827e1c)

It can't be an other issue ? It's look like the program stopping directly (beacause not found mic ?)

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/e4e99220-7950-46b2-b5dc-4d0b13515b2f)

**Comment by kbn53** [comment]
@nickpourazima It's working with my new mic !

I change my wire too and all is ok.

Now I cut my jack to directly connect into my old mic but I don't understand how I can solder this mic with just 1 cable with the TRS 2 cable (red and black)

![441443157_1161403548220927_2184741726975695367_n](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/f9570c57-a331-46bc-9952-8ca00f2e9fa5)![441447685_817377793786435_9152762180314767631_n](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/6426a1e4-ee33-4312-bf14-b1aab001f5ad)

Do you have any idea ?

**Comment by nickpourazima** [comment]
Hey @kbn53, glad to hear the other mic is working out for you!

This looks like a mono mic, so you only need to solder to the T (for the primary channel) and S (by uncoiling the ground shield wires around the microphone signal wire. The R channel will be empty.

**Comment by kbn53** [comment]
> Hey @kbn53, glad to hear the other mic is working out for you!
> 
> 
> 
> This looks like a mono mic, so you only need to solder to the T (for the primary channel) and S (by uncoiling the ground shield wires around the microphone signal wire. The R channel will be empty.

Big thanks for the follow up !

Sorry I don't understand very well, 

What cable I need to do here ?

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/ab409a37-ebca-4b5f-a201-eb3dff0cdf4c)

And here, if I understand correctly, I need to put one green on the S and the other one on the L (for T)

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/37fdbfe7-d522-49fe-b02b-bebd3294e3d1)

**Comment by nickpourazima** [comment]
Actually if you can fit that whole mic cable inside the mouthpiece are you can just wrap the wires around the screw terminals instead of needing to solder:
![334207319-ab409a37-ebca-4b5f-a201-eb3dff0cdf4c](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/12181252/4fb89777-bd97-4b3d-a0cf-468c8cd9badb)

**Comment by kbn53** [comment]
> Actually if you can fit that whole mic cable inside the mouthpiece are you can just wrap the wires around the screw terminals instead of needing to solder. Alternatively you can clip that mic cable so that it's shorter and then strip the wires and connect them to the screw terminals:
> 
> ![334207319-ab409a37-ebca-4b5f-a201-eb3dff0cdf4c](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/12181252/4fb89777-bd97-4b3d-a0cf-468c8cd9badb)
> 
> 
> 
> 

Hmm ok

I tried this but nothing happened

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/845aee3c-2c87-45fd-a721-fc013da5ea50)
![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/d4df3218-6c75-4ea9-839e-76c987201b55)

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/0afe417d-01d2-4978-9926-ea24b921c40d)

Do I need to strip the blue/grey wire ? You can see this one on my list picture.

**Comment by nickpourazima** [comment]
Did you unscrew the terminal and wrap the wires around it? 
![signal-2024-05-27-19-07-54-765](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/12181252/e1c39748-ee90-46ae-95b6-e3be6621f0d0)

**Comment by kbn53** [comment]
> Did you unscrew the terminal and wrap the wires around it? 
> 
> ![signal-2024-05-27-19-07-54-765](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/12181252/e1c39748-ee90-46ae-95b6-e3be6621f0d0)
> 
> 

Yes, I try this and directly on the trs, nothing happened.

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/2679442b-ac8b-4349-886f-21e3d230ad1f)
![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/d545a97c-ed94-4347-b0d3-032d4b0f4f7e)

**Comment by nickpourazima** [comment]
Sometimes the wires might be insulated. If you have a piece of sandpaper you can gently rub off the insulation so there's better conductivity. Chrcj

**Comment by kbn53** [comment]
> Sometimes the wires might be insulated. If you have a piece of sandpaper you can gently rub off the insulation so there's better conductivity. Also, check the wire with your multimeter set to continuity mode (the diode symbol):
> 
> 
> 
> https://m.youtube.com/watch?v=9IOFGcl_29U
> 
> 
> 
> Last, for your mic test - make sure you're connecting to the proper terminals on the male TRS connector. The copper should be GND, the other wire is the L channel. 

I don't understand what wrong....

I try with a new mic and connect my red cable on the L and the copper on the GND.

But nothings happens.

I try too the continuity but nothing, very weird.

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/3a0be9b5-f6d9-492a-b68f-1aa2f44a53c4)

 

![image](https://github.com/nickpourazima/rotary-phone-audio-guestbook/assets/71877652/53014b38-a15f-4d45-9f3b-268fc169d1a4)

**Comment by kbn53** [comment]
FINALY !

It's working.

I must have burnt the cable to remove the protection. After this it's working.

https://www.youtube.com/watch?v=WlRyQe-O5ME

A big thanks @nickpourazima for your follow up !
