### ISSUE TITLE
Error Starting the service

### ISSUE THREAD

**Issue by zeph51** [nickpourazima/rotary-phone-audio-guestbook#4]
Hello

Thanks for your work. I'm trying to setup a audio guestbook on my Rpi 3b but when I try to launch the service i've got this message : 

`Failed to start home-clement-rotary\x2dphone\x2daudio\x2dguestbook-audioGuestBook.service.mount: Unit home-clement-rotary\x2dphone\x2daudio\x2dguestbook-audioGuestBook.service.mount not found`

I don't understand where does it come from.

**Comment by nickpourazima** [comment]
Hey! Sorry for the late reply, I didn't get an email notification about this. The error you provided suggests a few things:

1. The error message references a `.mount` unit: `home-clement-rotary\x2dphone\x2daudio\x2dguestbook-audioGuestBook.service.mount`. However, it seems like you intended to reference a `.service` unit.
  
2. The use of `\x2d` is the encoding for a dash (`-`). Systemd uses this encoding in the filesystem paths to avoid naming conflicts.

Given the information provided, here's what you can do to troubleshoot:

1. **Check the service unit file name**: Make sure the service file is named correctly. If you're trying to start a service, the file should have the extension `.service`, and it should be located in one of the systemd configuration directories, typically `/etc/systemd/system/` or `/lib/systemd/system/`. 

    For example, if you are trying to start `audioGuestBook.service`, then the filename should be `audioGuestBook.service`.

2. **Reload systemd daemon**: Whenever you add or modify a systemd service unit file, you need to reload the systemd configuration. This will make systemd aware of the changes.

   ```bash
   sudo systemctl daemon-reload
   ```

3. **Check the service unit file content**: Open the service unit file using a text editor (like `nano` or `vim`) and make sure the content is correctly formatted and the `[Service]`, `[Unit]`, etc. sections are correctly filled out. If the service depends on a specific mount point, ensure that the corresponding `.mount` unit exists and is functional.

4. **Start the service**: Once you've verified the service unit file name and content, and reloaded the systemd daemon, attempt to start the service again:

   ```bash
   sudo systemctl start audioGuestBook.service
   ```

5. **Check the status and logs**: If the service fails to start, you can get more detailed logs with:

   ```bash
   sudo systemctl status audioGuestBook.service
   journalctl -xe
   ```

Following these steps should help you identify and fix the issue. If the problem persists, feel free to provide more details about the content of the service unit file or any other related configurations, and I'd be happy to assist further.

**Comment by nickpourazima** [comment]
Hey @zeph51, any issues after trying the recommendations above?
