### ISSUE TITLE
Serve audio files to endpoint 

### ISSUE THREAD

**Issue by nickpourazima** [nickpourazima/rotary-phone-audio-guestbook#47]
Instead of having to `scp` or mount as a network drive, or even physically remove the SD card and copy the audio files over we should consider pushing the data to a web server or add the ability to access the data via an endpoint

**Comment by jmdevita** [comment]
I may be interested working on this as local file saving can serve as a redundancy system. Seems like a flask service operating as a endpoint / website can do the trick.

**Comment by nickpourazima** [comment]
That would be fantastic, thank you!

**Comment by jmdevita** [comment]
Pull Request #52 Created

**Comment by nickpourazima** [comment]
Thank you @jmdevita for developing this!
